import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colores } from './fuentesyColores';

export const stylesCrearPublicacion = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: '#F5F7F8',
  },
  header: {
    width: '100%',
    height: 60,
    backgroundColor: colores.primario,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  backButton: {
    marginRight: 10,
    marginTop: Platform.OS === 'ios' ? 10 : 0,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 10,
    marginTop: Platform.OS === 'ios' ? 10 : 0,
  },
  form: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 10,
  },
  label: {
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 2,
    marginTop: 10,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: '#fff',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingRight: 8,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 1,
  },
  input: {
    flex: 1,
    padding: 10,
    fontSize: 15,
    color: '#222',
    fontStyle: 'italic',
    backgroundColor: 'transparent',
  },
  iconInput: {
    marginLeft: 2,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
    marginTop: 2,
  },
  turnoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 2,
  },
  turnoOpcion: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 18,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    marginRight: 5,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: {
    borderColor: '#03A9E0',
    backgroundColor: '#03A9E0',
  },
  turnoText: {
    fontSize: 13,
    color: '#444',
    marginRight: 2,
  },
  textArea: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    fontSize: 15,
    minHeight: 70,
    marginBottom: 20,
    marginTop: 5,
    textAlignVertical: 'top',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
    elevation: 2,
  },
  boton: {
    backgroundColor: colores.primario,
    borderRadius: 8,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  botonTexto: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    width: '80%',
    maxHeight: 250,
    elevation: 5,
  },
  modalItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  }
});
